# Generated by Django 4.2.7

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен состоять из 12 цифр', regex='^\\d{12}$')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='КПП должен состоять из 9 цифр', regex='^\\d{9}$')], verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='ОГРН должен состоять из 13 цифр', regex='^\\d{13}$')], verbose_name='ОГРН')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('okved', models.CharField(blank=True, max_length=100, null=True, verbose_name='Основной ОКВЭД')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('authorized_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Уставной капитал')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('liquidated', 'Ликвидирован'), ('reorganized', 'Реорганизован')], default='active', max_length=20, verbose_name='Статус')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['inn'], name='clients_cli_inn_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_cli_status_idx'),
        ),
    ]

