# Generated by Django 4.2.7 on 2025-10-31 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_inn_b65595_idx',
            old_name='clients_cli_inn_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_status_ce0d15_idx',
            old_name='clients_cli_status_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен состоять из 10 или 12 цифр', regex='^\\d{10}$|^\\d{12}$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='ОГРН должен состоять из 13 или 15 цифр', regex='^\\d{13}$|^\\d{15}$')], verbose_name='ОГРН'),
        ),
    ]
