# Generated by Django 4.2.7 on 2025-10-31 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_cli_inn_idx_clients_cli_inn_b65595_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='ИНН должен состоять из 10 или 12 цифр', regex='^\\d{10}$|^\\d{12}$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое наименование'),
        ),
    ]
